# docker-compose.yml
version: '3.10'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_innovation
    environment:
      DJANGO_SETTINGS_MODULE: ecommerce_innovation.settings

    command: bash -c "./run.sh"
    ports:
      - "8000:8000"
#    volumes:
#      - ./app:/app

networks:
  default:
    name: ecommerce_innovation
