# Generated by Django 4.1.6 on 2024-02-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('seller', 'SELLER'), ('buyer', 'BUYER')], default='buyer', max_length=10, verbose_name='User type'),
        ),
    ]
