# Generated by Django 4.1.6 on 2024-02-06 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=40, verbose_name='State')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('street_number', models.CharField(blank=True, max_length=40, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, max_length=40, verbose_name='Street Name')),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name='ZIP')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
    ]
