# Generated by Django 4.1.6 on 2024-02-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('total_amount', models.FloatField(default=0, verbose_name='Total amount')),
                ('total_quantity', models.FloatField(default=0, verbose_name='Total quantity')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Daily Data',
                'verbose_name_plural': 'Daily Data',
            },
        ),
    ]
